// ═══════════════════════════════════════════
// KNBMP · PGA-72 · MASTER DATA
// 72 Pilar Fondasional — 9 Domain
// Sumber: daftar-isi-72-dokument-.txt
// ═══════════════════════════════════════════

export interface Pillar {
  id: number;
  code: string;
  name: string;
  eng: string;
  desc: string;
  domain: number;
  domainColor: string;
  badge: 'foundation' | 'strategic' | 'operational';
  vision: string;
  dimensions: { label: string; value: string }[];
  principles: string[];
  xref: number[];
}

export interface Domain {
  id: number;
  code: string;
  emoji: string;
  name: string;
  nameId: string;
  nameSubtitle: string;
  range: string;
  color: string;
  bgColor: string;
  borderColor: string;
  description: string;
  pillars: Pillar[];
}

export const domains: Domain[] = [
  {
    id: 1,
    code: 'D1',
    emoji: '🏛️',
    name: 'Identity & Civilization',
    nameId: 'Identitas & Peradaban',
    nameSubtitle: 'Ruh & Jati Diri',
    range: 'PGA-01 — PGA-08',
    color: '#C4952A',
    bgColor: 'rgba(196,149,42,0.08)',
    borderColor: 'border-l-[#C4952A]',
    description: 'Domain ini adalah jantung spiritual KNBMP. Di sini kita mendefinisikan siapa kita, dari mana kita berasal, dan untuk apa kita ada. Tanpa 8 pilar ini, KNBMP hanyalah korporasi tanpa jiwa.',
    pillars: [
      {
        id: 1, code: 'PGA-01', name: 'Bintang Utara Peradaban', eng: 'Vision Statement',
        desc: 'Dalam tangan Anda kini terdapat 72 dokumen. Bukan 72 laporan biasa. Bukan 72 proposal. Melainkan 72 fondasi peradaban — yang dirancang dengan keyakinan bahwa sistem ekonomi rakyat yang benar-benar berdaulat adalah mungkin, dapat dibangun, dan sudah seharusnya ada sejak lama. Setiap dokumen dalam seri PGA-72 ini lahir dari pertanyaan yang sama: Bagaimana sistem yang benar-benar melayani rakyat — bukan sekadar mengklaim melayani rakyat — dapat dibangun, dijalankan, diukur, dan diwariskan? Indonesia berdiri di persimpangan sejarah yang luar biasa. Dengan 278 juta jiwa, 64,2 juta UMKM, 83.763 desa, dan potensi laut terluas di dunia — kita memiliki semua bahan untuk menjadi kekuatan ekonomi rakyat terbesar di abad ke-21. Yang selama ini kurang bukan sumber dayanya. Yang kurang adalah sistemnya. Arsitekturnya. Ekosistemnya. PGA-72 adalah arsitektur itu. Dokumen-dokumen ini dibuat dalam kerangka berpikir peradaban — dengan horizon 100 tahun, dengan tanggung jawab kepada generasi yang belum lahir, dengan kesadaran bahwa setiap kata yang kita tulis hari ini akan membentuk keputusan, kebijakan, dan kehidupan jutaan manusia di masa depan.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Membangun Ekosistem Ekonomi Rakyat Berdaulat yang Menjadikan Setiap Manusia Bebas, Makmur, dan Berdaya — dari Desa ke Dunia."',
        dimensions: [
          { label: 'Horizon Waktu', value: '100 Tahun (2025–2125)' },
          { label: 'Cakupan', value: '83.763 Desa, 38 Provinsi → Asia → Dunia' },
          { label: 'Populasi', value: '278 Juta Jiwa' },
          { label: 'UMKM', value: '64,2 Juta UMKM' },
          { label: 'Versi', value: 'Sovereign-72 Edition' },
          { label: 'Tier', value: 'Standar Emas Kelas Dunia' },
          { label: 'Jumlah Dokumen', value: '72 Dokumen — 9 Domain' },
          { label: 'Entitas Pemilik', value: 'Koperasi Korporasi Multipihak' },
        ],
        principles: [
          'Kedaulatan ekonomi rakyat sebagai tujuan tertinggi yang tidak bisa ditawar',
          'Keberlanjutan lintas generasi: keputusan hari ini harus relevan 100 tahun ke depan',
          'Inklusi total: tidak ada satu pun desa yang tertinggal dalam arsitektur ini',
          'Kemandirian sebagai fondasi, kerja sama sebagai perluasan — bukan ketergantungan',
          'Peradaban baru yang memanusiakan manusia, bukan mengobjektifikasi',
          'Kemakmuran bukan hak istimewa — ia adalah hak asasi setiap manusia',
          'Kita membangun untuk generasi yang belum lahir — itulah amanah yang kita pikul',
          'Setiap kata dipilih dengan hati-hati, setiap kalimat mengandung amanah — dokumen ini akan dibaca oleh cucu kita',
          'Mengubah sistem ekonomi membutuhkan doktrin yang jelas, sistem yang kokoh, tata kelola yang amanah, teknologi yang inklusif, dan manusia yang percaya bahwa perubahan adalah mungkin',
        ],
        xref: [7, 8, 9, 71],
      },
      {
        id: 2, code: 'PGA-02', name: 'Mandat Transformasi Nyata', eng: 'Mission Statement',
        desc: 'Tiga aksi nyata: Mengorganisir, Menguatkan, dan Menghubungkan rakyat Indonesia dalam ekosistem ekonomi digital yang berkeadilan.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Mentransformasi ekosistem ekonomi rakyat dari objek pembangunan menjadi subjek kedaulatan — melalui koperasi multipihak yang menghubungkan setiap desa, setiap potensi, dan setiap mimpi menjadi kekuatan nyata yang tak terbantahkan."',
        dimensions: [
          { label: 'Misi Inti', value: 'Mengorganisir, Menguatkan, Menghubungkan' },
          { label: 'Mekanisme', value: 'Koperasi Korporasi Multipihak' },
          { label: 'Target Awal', value: '10.000 Anggota (2026)' },
          { label: 'Target Puncak', value: '50.000.000 Anggota (2050)' },
          { label: '5 Bidang', value: 'Ekonomi, Pendidikan, Teknologi, Sosial, Keadilan' },
        ],
        principles: [
          'Visi = APA yang kita inginkan (Destinasi), Misi = BAGAIMANA kita mencapainya (Jalan)',
          'Mengorganisir: Kekuatan terbesar bukan di tangan segelintir orang, tapi di tangan rakyat yang bersatu',
          'Menguatkan: Yang terbaik yang bisa kami lakukan untuk mereka adalah membuat mereka tidak perlu kami lagi',
          'Menghubungkan: Konektivitas adalah kunci kemakmuran — menghapus walls yang memisahkan dari kesempatan',
          'Transformasi nyata, bukan retorika: setiap kata harus memiliki padanan dalam tindakan terukur',
          'Akuntabilitas total: setiap janji harus dapat diverifikasi oleh setiap anggota',
        ],
        xref: [1, 3, 9, 13, 25, 33],
      },
      {
        id: 3, code: 'PGA-03', name: 'Akar Hikmah Para Pendiri', eng: "Founders' Philosophy & Guiding Principles",
        desc: 'Diagnosis 7 Luka Besar Indonesia — fragmentasi 64,2 juta UMKM, ketergantungan kapital asing, 97+ juta unbanked, 22.000+ koperasi zombie, 17.500+ desa tertinggal — yang melahirkan 5 Blind Spot dan 5 Prinsip Fundamental pendiri. Hikmah ditarik dari gotong royong Nusantara, muamalah Islam, Mondragón/Fonterra/Rabobank, TVE China, Ubuntu Afrika, dan Amul India.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Saya bermimpi Indonesia di mana setiap petani punya akses pasar yang fair, setiap nelayan bisa mengirim ikan segar ke mana pun, setiap UMKM naik kelas dari informal ke formal, dan setiap anggota memiliki suara dalam keputusan ekonomi — dan saya yakin: ini bukan mimpi, ini adalah misi yang bisa dicapai jika kita bangun bersama." — Prabu Danling',
        dimensions: [
          { label: '7 Luka Besar', value: 'Fragmentasi UMKM, Kapital Asing, Kesenjangan Akses, Koperasi Zombie, Desa Tertinggal, Hilangnya Identitas, Kosongnya Model Alternatif' },
          { label: 'Wisdom Nusantara', value: 'Gotong Royong, Subak Bali, Ladang Berkelanjutan, Kongsi Laut' },
          { label: 'Wisdom Islam', value: 'Muamalah, Zakat, Waqf, Mudharabah, Qirad' },
          { label: 'Model Barat', value: 'Mondragón (€11B+), Fonterra ($20B+), Rabobank ($70B+)' },
          { label: 'Model Global', value: 'TVE China, Ubuntu Afrika, Amul India, SHG India' },
          { label: '5 Blind Spots', value: 'Market Will Solve Everything, Technology Will Democratize, Government Will Take Care, Scale vs Community, Profit vs Purpose' },
          { label: '7 Impian Pendiri', value: 'Ekonomi Berdaulat, Konektivitas, Demokrasi, Teknologi Rakyat, Kelestarian, Model Dunia, Warisan Generasi' },
        ],
        principles: [
          'Rakyat Pertama, Selalu: setiap keputusan dimulai dengan pertanyaan "Apa yang terbaik untuk rakyat?" — bukan untuk profit, investor, atau manajemen',
          'Kita Bangun Bersama, Bukan Untuk Kita: KNBMP dimiliki oleh anggota, founder tidak punya equity khusus, perencanaan suksesi dimulai dari hari pertama',
          'Sistem yang Membangun: tujuannya kemandirian bukan ketergantungan — "Yang terbaik yang bisa kami lakukan untuk mereka adalah membuat mereka tidak perlu kami lagi"',
          'Kecil-kecil Dulu: mulai dari fondasi — 10.000 anggota (2026) → 1 juta (2030) → 5 juta (2035) — bukti konsep dulu, scale setelah terbukti',
          'Dunia Sudah Cukup Baik: tidak reinvent the wheel — gotong royong, muamalah, cooperative sudah ada, KNBMP menggabungkan semua dalam ekosistem terintegrasi',
          'Pasar adalah ALAT, bukan TUAN: perlu ada entitas yang memastikan pasar bekerja fair untuk semua, bukan hanya untuk yang kuat',
          'Teknologi harus DIKONTROL oleh rakyat: KNBMP membangun infrastruktur sendiri agar teknologi membebaskan, bukan menguasai',
        ],
        xref: [1, 2, 4, 5, 6, 50, 54],
      },
      {
        id: 4, code: 'PGA-04', name: 'Sejarah & Luka yang Menyembuhkan', eng: 'Story of Origin / Narrative',
        desc: 'Narasi asal-usul KNBMP lahir dari 3 warga negara yang dikhianati sistem — Pak Hasan (petani kopi Bromo), Pak Jusuf (nelayan Takalar), Bu Ratna (wirausaha Kupang) — yang menghadapi 6 Rantai Penindasan Struktural. Evolusi dari bisnisPPP (2016–2019) → JP3 (2020–2025) → KNBMP (2026) melalui 4 Identitas Pendiri: Gugun Gunara, Muhammad Lutfi Azmi, Prabu Danling, Santri Angon.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Dari luka kolonialisme 400 tahun, dari kemerdekaan yang belum sepenuhnya merdeka secara ekonomi, dari 3 warga negara yang dikhianati sistem — Pak Hasan, Pak Jusuf, Bu Ratna — lahirlah tekad yang tidak bisa dipatahkan: KNBMP, antitesis dari segala bentuk penindasan ekonomi terhadap rakyat."',
        dimensions: [
          { label: '3 Warga Dikhianati', value: 'Pak Hasan (Petani Kopi Bromo), Pak Jusuf (Nelayan Takalar), Bu Ratna (Wirausaha Kupang)' },
          { label: '6 Rantai Penindasan', value: 'Monopoli Tengkulak, Akses Keuangan, Pembiayaan, Logistik, Informasi, Representasi' },
          { label: 'Evolusi Organisasi', value: 'bisnisPPP (2016–2019) → JP3 (2020–2025) → KNBMP (2026)' },
          { label: 'Kronologi Kunci', value: '2016 (Konsep) → 2018 (Pilot) → 2020 (JP3) → 2022 (Skala) → 2024 (Negosiasi) → 2026 (KNBMP)' },
          { label: '4 Identitas Pendiri', value: 'Gugun Gunara (Bisnis-Negara), M. Lutfi Azmi (Ruhani-Ilmiah), Prabu Danling (Visi Peradaban), Santri Angon (Kemanusiaan)' },
          { label: '7 Nilai Inti Asal', value: 'Amanah, Keadilan, Transparansi, Kemaslahatan, Kesederhanaan, Kebersamaan, Kelestarian' },
          { label: 'DNA Narasi', value: 'Dari penderitaan rakyat, oleh tekad kolektif, untuk kemerdekaan ekonomi sejati' },
        ],
        principles: [
          'Mengakui luka adalah langkah pertama penyembuhan: KNBMP lahir dari pengakuan bahwa sistem saat ini telah gagal melindungi rakyat',
          '3 Wajah Rakyat: Pak Hasan (petani yang dihina tengkulak), Pak Jusuf (nelayan yang ikannya membusuk tanpa cold chain), Bu Ratna (UMKM yang ditolak bank) — mereka adalah alasan KNBMP ada',
          'Evolusi, bukan revolusi: dari bisnisPPP ke JP3 ke KNBMP — setiap tahap membangun fondasi untuk tahap berikutnya',
          '4 Identitas Pendiri memastikan KNBMP tidak terjebak dalam satu perspektif — bisnis, ruhani, peradaban, dan kemanusiaan harus selalu seimbang',
          'Sejarah bukan beban, melainkan guru: 400 tahun kolonialisme, 80 tahun kemerdekaan ekonomi semu — semua menjadi bahan bakar tekad',
          'KNBMP bukan proyek bisnis biasa: ia adalah jawaban historis terhadap pertanyaan "Mengapa rakyat Indonesia masih miskin di negara yang kaya?"',
          'Transformasi membutuhkan narasi yang membebaskan, bukan narasi yang mengikat — setiap anggota harus merasa bahwa ia adalah bagian dari cerita ini',
        ],
        xref: [1, 2, 3, 5, 6, 7, 71],
      },
      {
        id: 5, code: 'PGA-05', name: 'Sepuluh Pilar Etika Absolut', eng: 'Core Values Charter',
        desc: '10 Nilai Inti yang menjadi DNA moral KNBMP — Amanah (4 dimensi), Keadilan (distributif/prosedural/interaksional/retributif), Transparansi (imunitas korupsi), Kemaslahatan (filter tertinggi), Kesederhanaan (besar tanpa berlebihan), Kebersamaan (yang mengangkat), Kelestarian (bertanggung jawab), Keberanian (yang membangun), Kejujuran (tidak kompromi), dan Kemandirian (berdaulat). Setiap nilai memiliki definisi, dimensi, implementasi, antitesis, metrik, dan koneksi peradaban dunia.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Ada nilai-nilai yang tidak bisa ditawar, tidak bisa dikompromikan, dan tidak bisa dilupakan — Amanah, Keadilan, Transparansi, Kemaslahatan, Kesederhanaan, Kebersamaan, Kelestarian, Keberanian, Kejujuran, Kemandirian — mereka adalah sepuluh pilar yang menjadi DNA moral KNBMP, berlaku untuk semua orang dari anggota hingga direktur."',
        dimensions: [
          { label: '1. Amanah (Trust)', value: '4 dimensi: kepada Anggota, Mitra, Masyarakat, Diri Sendiri — mata uang tertinggi KNBMP' },
          { label: '2. Keadilan (Justice)', value: '4 dimensi: Distributif (kontribusi), Prosedural (suara semua), Interaksional (hormat), Retributif (sanksi adil)' },
          { label: '3. Transparansi', value: 'Imunitas terhadap korupsi — keterbukaan mutlak sebagai standar default organisasi' },
          { label: '4. Kemaslahatan', value: 'Filter tertinggi: setiap keputusan harus lolos uji "Apakah ini untuk kemaslahatan bersama?"' },
          { label: '5. Kesederhanaan', value: 'Besar tanpa berlebihan — efisiensi operasional dan eliminasi pemborosan di semua level' },
          { label: '6. Kebersamaan', value: 'Kebersamaan yang mengangkat — gotong royong modern yang melampaui sekadar kerja sama' },
          { label: '7. Kelestarian', value: 'Kelestarian yang bertanggung jawab — setiap keputusan memperhitungkan dampak 3 generasi ke depan' },
          { label: '8–10. Tiga Nilai Baru', value: 'Keberanian (yang membangun, bukan merusak), Kejujuran (tanpa kompromi), Kemandirian (berdaulat, bukan bergantung)' },
        ],
        principles: [
          '10 nilai ini bersifat absolut — tidak ada keadaan, tekanan, atau otoritas yang membenarkan pelanggaran terhadap satupun dari nilai ini',
          'Setiap keputusan strategis harus melewati uji kesepuluh nilai ini — jika satu gagal, keputusan harus direvisi',
          'Pelanggaran etika oleh siapa pun — termasuk pendiri, direksi, dan pengawas — tetap pelanggaran yang harus diproses secara adil',
          'Budaya etika dibangun dari atas (contoh pimpinan) dan dijalankan dari bawah (peer accountability)',
          'Amanah bukan sekadar tidak mencuri — ia adalah menjaga semua yang dipercayakan: uang, data, waktu, mimpi, dan reputasi anggota',
          'Keadilan berarti 1 Anggota = 1 Suara — bukan 1 Modal = 1 Suara. Distribusi SHU berdasarkan kontribusi nyata, bukan besaran deposit',
          'Kemandirian sebagai tujuan akhir: sistem yang membangun harus membuat anggota TIDAK PERLU KNBMP lagi karena sudah bisa berdiri sendiri',
        ],
        xref: [1, 2, 3, 4, 6, 22, 54, 55],
      },
      {
        id: 6, code: 'PGA-06', name: 'Antitesis Sistem Global', eng: 'Identity & Positioning Paper',
        desc: 'KNBMP Positioning vs Kapitalisme, Sosialisme, dan Model Lain melalui 5 Axis Diferensiasi (Governance, Ownership, Purpose, Technology, Scale) dengan 10 Key Positioning Statements. KNBMP bukan anti-kapitalisme, bukan anti-sosialisme — ia adalah model ke-3 yang menggabungkan efisiensi pasar dengan keadilan sosial. Competitive landscape analysis menunjukkan celah yang tidak dimiliki siapapun: koperasi digital-native berbasis desa.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"KNBMP bukan sekadar alternatif — ia adalah antitesis. Antitesis terhadap sistem yang telah gagal mensejahterakan mayoritas. Kami menggabungkan efisiensi pasar dengan keadilan sosial, skalabilitas teknologi dengan kehangatan komunitas, dan profitabilitas dengan purpose — bukan kompromi, tapi sintesis."',
        dimensions: [
          { label: 'Axis 1: Governance', value: '1 Anggota = 1 Suara (bukan 1 Modal = 1 Suara seperti korporasi, atau 1 Partai = 1 Suara seperti negara)' },
          { label: 'Axis 2: Ownership', value: 'Dimiliki anggota secara kolektif melalui Koperasi — bukan shareholder, bukan negara' },
          { label: 'Axis 3: Purpose', value: 'Kesejahteraan anggota sebagai tujuan utama — bukan shareholder value, bukan GDP growth' },
          { label: 'Axis 4: Technology', value: 'Digital-native, dimiliki rakyat, dibangun untuk inklusi — bukan platform ekstraksi data' },
          { label: 'Axis 5: Scale', value: 'Skala nasional (83.763 desa) tetapi tetap personal di level desa — bukan top-down, bukan bottom-only' },
          { label: 'vs Kapitalisme', value: 'Profit untuk segelintir → SHU untuk semua anggota; shareholder → member-owner; eksploitasi → pemberdayaan' },
          { label: 'vs Sosialisme', value: 'Negara mengontrol → anggota berdaulat; inefisiensi birokrasi → efisiensi koperasi; top-down → bottom-up' },
          { label: '4 Identitas Kunci', value: 'Integrasi Gugun Gunara (Bisnis), M. Lutfi Azmi (Ruhani), Prabu Danling (Peradaban), Santri Angon (Kemanusiaan)' },
        ],
        principles: [
          'KNBMP tidak anti-kapitalisme — KNBMP anti-ketidakadilan: pasar adalah alat, bukan tuan; profit adalah hasil, bukan tujuan',
          'Posisi yang jelas membutuhkan keberanian untuk tidak menyenangkan semua pihak — clarity lebih berharga kuin popularity',
          '5 Axis Diferensiasi (Governance, Ownership, Purpose, Technology, Scale) adalah fondasi identitas yang tidak bisa ditiru kompetitor',
          'KNBMP adalah model ke-3: bukan kapitalisme (profit-centric), bukan sosialisme (state-centric), melainkan kooperatisme rakyat (people-centric)',
          'Competitive advantage terletak pada celah unik: tidak ada entitas lain yang menggabungkan koperasi + digital-native + skala nasional + berbasis desa',
          'Identitas dibangun dari apa yang kita lawan DAN apa yang kita bangun — kritik tanpa alternatif adalah keluhan; alternatif tanpa aksi adalah ilusi',
          '4 Identitas Pendiri memastikan positioning tidak terjebak dalam satu dimensi: bisnis yang bermoral, moral yang bisnis-aware, visi yang actionable, kemanusiaan yang scalable',
        ],
        xref: [1, 3, 4, 5, 7, 8, 15, 57],
      },
      {
        id: 7, code: 'PGA-07', name: 'Deklarasi Pembebasan Ekonomi', eng: 'Manifesto / Declaration of Purpose',
        desc: 'Manifesto KNBMP berisi Deklarasi Kemerdekaan Ekonomi, 10 Keyakinan (Tentang Rakyat, Ekonomi, Demokrasi, Teknologi, Keadilan, Kemandirian, Kebersamaan, Kelestarian, Peradaban, Masa Depan), Komitmen kepada Anggota/Masyarakat/Bangsa/Peradaban, dan Yang Ditolak (Eksploitasi, Ketimpangan, Korupsi, Ketergantungan, Kerusakan Lingkungan, Diskriminasi). Visi 2045: 10 juta anggota, 83.763 desa, Rp2.000T transaksi.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Kami menyatakan bahwa kemerdekaan ekonomi adalah hak asasi setiap manusia — bukan pemberian negara, bukan hadiah lembaga internasional, melainkan hak yang melekat pada martabat manusia itu sendiri. Visi 2045: 10.000.000 anggota, 83.763 desa terjangkau, Rp2.000 Triliun transaksi — Indonesia menjadi model ekonomi rakyat bagi dunia."',
        dimensions: [
          { label: '10 Keyakinan', value: 'Tentang Rakyat, Ekonomi, Demokrasi, Teknologi, Keadilan, Kemandirian, Kebersamaan, Kelestarian, Peradaban, Masa Depan' },
          { label: '4 Komitmen', value: 'Kepada Anggota (hak & kedaulatan), Masyarakat (dampak positif), Bangsa (Indonesia berdaulat), Peradaban (model dunia)' },
          { label: 'Yang Ditolak', value: 'Eksploitasi, Ketimpangan, Korupsi, Ketergantungan, Kerusakan Lingkungan, Diskriminasi — 6 hal yang tidak bisa dikompromikan' },
          { label: 'Visi 2045', value: '10.000.000 Anggota, 83.763 Desa, Rp2.000T Transaksi' },
          { label: 'Anti-Oligarki', value: 'Mekanisme yang mencegah konsentrasi kekuasaan — Pentagon Kedaulatan memastikan tidak ada satu pihak mendominasi' },
          { label: 'Panggilan Aksi', value: 'Bergabunglah — bukan sebagai penonton, melainkan sebagai arsitek masa depan ekonomi rakyat Indonesia' },
          { label: 'Kutipan Pendiri', value: '4 kutipan inspiratif dari Gugun Gunara, M. Lutfi Azmi, Prabu Danling, Santri Angon — fondasi moral manifest' },
        ],
        principles: [
          'Deklarasi ini bersifat permanen dan tidak dapat dicabut oleh entitas apa pun — ia adalah konstitusi moral KNBMP',
          'Kemerdekaan ekonomi dimulai dari kesadaran rakyat, diwujudkan melalui aksi kolektif, dan dijaga oleh setiap anggota',
          '10 Keyakinan bukan slogan — setiap keyakinan memiliki padanan dalam kebijakan, SOP, dan KPI yang terukur',
          '6 Hal yang Ditolak bukan sekadar daftar — setiap poin memiliki mekanisme pencegahan dan penegakan yang konkret',
          'Anti-Oligarki: Pentagon Kedaulatan (5 KPA masing-masing 20% suara) memastikan kekuasaan tidak terkonsentrasi',
          'Visi 2045 bukan angka kosong — ia didukung oleh roadmap 3 fase (Fondasi 2026–2030, Skala 2030–2035, Maturasi 2035–2050)',
          'Setiap anggota adalah penjaga deklarasi — jika manifest ini dikhianati, anggota berhak dan berkewajiban untuk memperbaiki',
        ],
        xref: [1, 2, 3, 4, 5, 6, 8, 17, 22, 71],
      },
      {
        id: 8, code: 'PGA-08', name: 'Arsitektur Konseptual Makro', eng: 'Whitepaper',
        desc: 'Whitepaper KNBMP: latar belakang 26 juta miskin, Gini 0.38, 64,2 juta UMKM. Dual-Entity Model: JE-P3 (strategy) + KNMP (operations) dengan Pentagon Kedaulatan (5 KPA masing-masing 20% suara) dan 7-Tier Membership (Petani GRATIS hingga KORNAS Rp200M). 4 Inovasi Fundamental, 6 revenue streams, 7 keunggulan kompetitif, dan 3 fase eksekusi (Fondasi 2026–2030, Skala 2030–2035, Maturasi 2035–2050). 17 pendiri, target 10 juta anggota.',
        domain: 1, domainColor: '#C4952A', badge: 'foundation',
        vision: '"Arsitektur PGA-72 bukan kumpulan dokumen yang berdiri sendiri — ia adalah organisme hidup yang saling terhubung. Dual-Entity (JE-P3 + KNMP) memastikan visi tetap tajam sementara operasi tetap agile. Pentagon Kedaulatan mencegah oligarki. 7-Tier Membership memastikan inklusi total. Target: 10.000.000 anggota, Rp2.000T transaksi, 83.763 desa."',
        dimensions: [
          { label: 'Latar Belakang', value: '26 Juta miskin, Gini 0.38, 64,2 Juta UMKM, 97+ Juta unbanked, 22.000+ KUD tidak aktif' },
          { label: 'Dual-Entity Model', value: 'JE-P3 (Asosiasi Strategi) + KNMP (Koperasi Operasi) — visi dan eksekusi terpisah tapi terintegrasi' },
          { label: 'Pentagon Kedaulatan', value: '5 KPA: Petani, Nelayan, UMKM, Profesional, Investor — masing-masing 20% suara, anti-oligarki' },
          { label: '7-Tier Membership', value: 'Petani (GRATIS) → Nelayan → UMKM → Koperasi → Profesional → Korporasi → KORNAS (Rp200M)' },
          { label: '4 Inovasi Fundamental', value: 'Pentagon Kedaulatan, 7-Tier Membership, 6 Unit Usaha Terintegrasi, Invisible Dues' },
          { label: 'Model Bisnis', value: '6 Revenue Streams: Marketplace, Fintech, Logistik, Edukasi, Ekspor-Impor, Data Insights' },
          { label: '3 Fase Eksekusi', value: 'Fondasi (2026–2030): 10K–1M anggota | Skala (2030–2035): 1M–5M | Maturasi (2035–2050): 5M–10M' },
          { label: '7 Kategori Risiko', value: 'Regulasi, Governance, Teknologi, Keuangan, Operasional, Reputasi, Geopolitik — masing-masing dengan mitigasi' },
        ],
        principles: [
          'Dual-Entity sebagai fondasi: JE-P3 menjaga strategi jangka panjang, KNMP menjaga eksekusi operasional — keduanya saling mengawasi',
          'Pentagon Kedaulatan mencegah dominasi: 5 KPA dengan suara seimbang memastikan tidak ada satu kelompok yang mendominasi keputusan',
          '7-Tier Membership memastikan inklusi total: dari petani GRATIS hingga korporasi — setiap level memiliki hak dan tanggung jawab yang proporsional',
          '4 Inovasi Fundamental (Pentagon, 7-Tier, 6 Unit Usaha, Invisible Dues) adalah keunggulan kompetitif yang tidak bisa ditiru karena membutuhkan ekosistem lengkap',
          '3 Fase eksekusi yang realistis: fondasi dulu (proof of concept), skala setelah terbukti, maturasi untuk jangka panjang — tidak ada lompatan berisiko',
          '7 Keunggulan Kompetitif: First Mover, Network Effects, Community Trust, Data Advantage, Gov Relations, Integrated Ecosystem, Anti-Oligarchy',
          'Whitepaper ini adalah peta, bukan wilayah — realitas selalu lebih kaya dari rencana, dan arsitektur ini dirancang untuk beradaptasi',
        ],
        xref: [1, 2, 3, 5, 6, 7, 9, 17, 18, 32, 41, 44, 45, 72],
      },
    ],
  },
  {
    id: 2,
    code: 'D2',
    emoji: '♟️',
    name: 'Strategy & Direction',
    nameId: 'Strategi & Arah',
    nameSubtitle: 'Navigasi & Arah Angin',
    range: 'PGA-09 — PGA-16',
    color: '#1565C0',
    bgColor: 'rgba(21,101,192,0.08)',
    borderColor: 'border-l-[#1565C0]',
    description: 'Domain ini adalah otak strategis. Bagaimana niat baik dan ruhani yang suci diterjemahkan menjadi taktik penguasaan pasar yang cerdas, tajam, dan tak tertandingi.',
    pillars: [
      { id: 9, code: 'PGA-09', name: 'Navigasi Dekade Pertama', eng: 'Strategic Masterplan 3–10 Years',
        desc: 'Peta jalan presisi dari tahun 2026 hingga 2036.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Peta jalan yang tidak hanya menunjukkan arah, tetapi juga mempersiapkan kita untuk badai yang pasti akan datang."',
        dimensions: [{ label: 'Cakupan', value: '10 Tahun Masterplan (2026–2036)' }, { label: 'Fase', value: '3 Fase Utama' }, { label: 'Milestone', value: '24 Titik Keberhasilan Kunci' }],
        principles: ['Setiap dekade harus memiliki tujuan terukur', 'Masterplan hidup, bukan dokumen mati', 'Ketahanan lebih penting dari kecepatan'],
        xref: [1, 8, 11, 25] },
      { id: 10, code: 'PGA-10', name: 'Arsitektur Nilai Multipihak', eng: 'Business Model & Value Architecture',
        desc: 'Bagaimana setiap KPA (Kelompok Pihak Anggota) berinteraksi, menghasilkan, dan berbagi kekayaan secara adil.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Nilai bukan apa yang kita klaim — nilai adalah apa yang dirasakan oleh setiap desa, setiap anggota, setiap mitra."',
        dimensions: [{ label: 'Sasaran', value: 'Anggota, Mitra, Pemerintah' }, { label: 'Diferensiasi', value: 'Kedaulatan vs. Eksploitasi' }],
        principles: ['Nilai harus terukur dan terverifikasi oleh penerima', 'Proposisi nilai berbeda untuk setiap segmen'],
        xref: [1, 2, 25, 29] },
      { id: 11, code: 'PGA-11', name: 'Peta Pertempuran & Lanskap Industri', eng: 'Market Landscape & Industry Map',
        desc: 'Analisis tajam atas medan perang ekonomi yang kita masuki.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Pertempuran ekonomi dimenangkan bukan oleh yang terbesar, tetapi oleh yang paling relevan bagi rakyat."',
        dimensions: [{ label: 'Arena', value: 'Ekonomi Rakyat & Desa' }, { label: 'Keunggulan', value: 'Jaringan Desa Terluas' }],
        principles: ['Fokus pada keunggulan unik yang tidak bisa disalin pesaing'],
        xref: [9, 12, 15, 61] },
      { id: 12, code: 'PGA-12', name: 'Strategi Penetrasi Urat Nadi', eng: 'Go-To-Market Strategy',
        desc: 'Cara kita merebut hati 83.763 desa tanpa harus membakar uang seperti startup konvensional.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Menembus urat nadi ekonomi rakyat bukan dengan kekerasan pasar, tetapi dengan relevansi yang tak bisa ditolak."',
        dimensions: [{ label: 'Pendekatan', value: 'Desa by Desa' }, { label: 'Target', value: '1.000 Desa Pioneer' }],
        principles: ['Penetrasi dimulai dari desa yang paling membutuhkan'],
        xref: [11, 13, 40, 61] },
      { id: 13, code: 'PGA-13', name: 'Dual-Track: Orkestrasi Ekosistem Desa', eng: 'Dual-Track Integration Strategy',
        desc: 'Setiap desa di Indonesia saat ini sudah memiliki rata-rata 15-25 lembaga, program, dan infrastruktur yang berjalan secara silo (terpisah-pisah tanpa koordinasi digital). Dari BUMDes, KUD, PKK, Posyandu, Gapoktan, P3A, Karang Taruna, hingga program Pamsimas — semuanya beroperasi dengan sistem administrasi manual, tidak terhubung satu sama lain, dan tidak memiliki platform digital terintegrasi. KNMP sebagai koperasi multi-pihak nasional memiliki peluang emas untuk menjadi "Digital Operating System Desa" — satu platform yang mengintegrasikan seluruh kelembagaan desa yang sudah ada ke dalam ekosistem digital tunggal via kopnusa.id. KNMP TIDAK menggantikan kelembagaan desa yang sudah ada — KNMP adalah Digital Nervous System yang menghubungkan semua lembaga, program, dan infrastruktur desa ke dalam satu platform. Posisi ini belum dimiliki oleh program manapun termasuk KDMP pemerintah yang hanya fokus gerai fisik tanpa sistem operasional digital yang siap pakai.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Kami bukan sekadar koperasi. Kami adalah Digital Nervous System yang menghubungkan seluruh infrastruktur desa menjadi satu ekosistem yang hidup, bernapas, dan berkembang bersama — dengan dukungan pemerintah atau tanpa dukungan pemerintah, kami akan tetap maju."',
        dimensions: [
          { label: 'LKD Wajib', value: 'RT, RW, PKK, Karang Taruna, Posyandu, LPM — 6 lembaga per desa' },
          { label: 'LKD Opsional', value: 'Linmas, Gapoktan, HIPPA, KIM, Pokmas — 5+ lembaga per desa' },
          { label: 'Badan Desa', value: 'BPD, BKAD, BUMDes, BUMDesMA, BAZDes — 5 badan formal' },
          { label: 'Program Sektoral', value: 'P3A, Poktan, KWT, Lumbung Pangan, KRPL, SPP, KUBE, Pamsimas, KUD, KDMP, Prukades, Desa Wisata — 12 program' },
          { label: 'Sistem Digital Pemerintah', value: 'SID, Prodeskel, DIGIDES, Siskeudes, SIPADES' },
          { label: 'Infrastruktur Fisik', value: 'Jalan desa, Irigasi, Pasar desa, Air bersih, Puskesmas, Sekolah, Balai desa, Internet/BTS' },
          { label: 'Gap KRITIS', value: 'PKK (83.763), Karang Taruna (83.763), Lumbung Pangan, BUMDesMA, Sistem Pemerintah' },
          { label: '6 Pilar Integrasi', value: 'Desa Cerdas Digital, Holding Desa, Resi Gudang Digital, Investasi & Kampung Modal, Logistik Digital, Unit Usaha Strategis' },
          { label: 'Super-App kopnusa.id', value: '12 modul: VMS, Health Dashboard, Agri Dashboard, Economy Tracker, Cooperative Governance, Marketplace, Fintech JP3 Pay, Logistics, Academy, Safety & Security, Cultural Heritage, Energy' },
          { label: 'Dual-Track', value: 'Track A (Pemerintah: MOU Kemendesa, API SID/Prodeskel, KDMP, Dana Desa Rp60,6T) + Track B (People Power: community mobilization, grassroots, independent funding)' },
          { label: 'Roadmap 3 Fase', value: 'Foundation (2026) → Scale (2027-2028) → Dominate (2029-2030)' },
          { label: 'Total Infrastruktur', value: '500.000+ unit kelembagaan, 1.850.000+ LKD, 45+ komponen' },
        ],
        principles: [
          'Bukan Menggantikan, tapi Menyatukan — KNMP adalah Digital Nervous System, bukan pesaing lembaga desa',
          'PKK sebagai Channel Utama — 30 juta kader sebagai agen KNMP ke level rumah tangga',
          'Karang Taruna Digital — pipeline agen logistik dan kader digital per desa',
          'BUMDesMA sebagai Mitra Strategis — jaringan antar-desa yang sudah berjalan',
          'Lumbung Pangan → Resi Gudang Digital — upgrade proto-gudang existing',
          'Interoperabilitas Data — kewajiban integrasi API dengan SID, Prodeskel, Siskeudes',
          'Silo Syndrome adalah Musuh Utama — memecahkan fragmentasi 500.000+ unit kelembagaan',
          '3 Fase: Foundation (2026) → Scale (2027-2028) → Dominate (2029-2030)',
          'Dual-track: Dua jalur, satu tujuan — tidak menunggu izin untuk bertindak, tapi selalu terbuka untuk kolaborasi',
          'Fleksibilitas strategis: kemandirian bukan kelemahan, kemandirian adalah bukti kepercayaan pada misi',
          'People power sebagai fondasi: perubahan sejati datang dari rakyat, bukan dari pemerintah',
          'Setiap pemangku kepentingan harus mendapat nilai yang nyata dari integrasi',
        ],
        xref: [9, 11, 12, 14, 17, 18, 21, 25, 26, 28, 34, 37, 40, 41, 44, 45, 60] },
      { id: 14, code: 'PGA-14', name: 'Gerbang Penaklukan Global', eng: 'Expansion / International Strategy',
        desc: 'Strategi membawa produk desa untuk merajai meja makan 195 negara.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Kedaulatan tidak berarti isolasi — ia berarti berhubungan dengan dunia dari posisi yang kuat."',
        dimensions: [{ label: 'Model', value: 'South-South Cooperation' }, { label: 'Target', value: '195 Negara' }],
        principles: ['Kemitraan harus setara, bukan simbiosis parasitisme'],
        xref: [13, 15, 37, 62] },
      { id: 15, code: 'PGA-15', name: 'Benteng Kedaulatan', eng: 'Competitive Moat & Advantage',
        desc: 'Mengapa KNBMP tidak akan bisa ditiru, dibeli, atau dihancurkan oleh konglomerat asing.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Kedaulatan yang tidak dilindungi adalah ilusi. Benteng ini memastikan setiap pilar tetap berdiri."',
        dimensions: [{ label: 'Ancaman', value: 'Ekonomi, Politik, Digital' }, { label: 'Perlindungan', value: 'Multi-layer Defense' }],
        principles: ['Kedaulatan harus dilindungi secara proaktif, bukan reaktif'],
        xref: [6, 11, 45, 66] },
      { id: 16, code: 'PGA-16', name: 'Skenario Krisis & Opsi Strategis', eng: 'Scenario Planning',
        desc: 'Rencana cadangan saat kita dihadapkan pada perubahan geopolitik, pandemi, atau krisis regulasi.',
        domain: 2, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Organisasi yang hanya merencanakan keberhasilan tidak siap menghadapi kenyataan."',
        dimensions: [{ label: 'Skenario', value: 'Best, Base, Worst Case' }, { label: 'Trigger', value: 'Early Warning System' }],
        principles: ['Setiap skenario krisis harus memiliki rencana respons yang jelas'],
        xref: [9, 39, 45, 64] },
    ],
  },
  {
    id: 3,
    code: 'D3',
    emoji: '⚖️',
    name: 'Governance & Legal',
    nameId: 'Tata Kelola & Hukum',
    nameSubtitle: 'Tatanan & Hukum Keadilan',
    range: 'PGA-17 — PGA-24',
    color: '#6A1B9A',
    bgColor: 'rgba(106,27,154,0.08)',
    borderColor: 'border-l-[#6A1B9A]',
    description: 'Keadilan tanpa hukum adalah angan-angan. Domain ini memastikan bahwa kedaulatan benar-benar ada di tangan anggota (1 Anggota = 1 Suara), dan tidak ada pengurus yang bisa menjadi tiran.',
    pillars: [
      { id: 17, code: 'PGA-17', name: 'Keseimbangan Kekuasaan', eng: 'Governance Charter',
        desc: 'Aturan main bagaimana Eksekutif, Pengawas, dan Anggota saling menjaga tanpa saling menghambat.',
        domain: 3, domainColor: '#6A1B9A', badge: 'strategic',
        vision: '"Kekuasaan tanpa keseimbangan adalah tirani. Keseimbangan tanpa kekuasaan adalah kekacauan."',
        dimensions: [{ label: 'Prinsip', value: '1 Anggota = 1 Suara' }, { label: 'Struktur', value: 'Checks & Balances' }],
        principles: ['Tidak ada satu pihak yang memiliki kekuasaan absolut'],
        xref: [18, 19, 22, 50] },
      { id: 18, code: 'PGA-18', name: 'Anatomi Kelembagaan', eng: 'Organizational Structure',
        desc: 'Bentuk struktur Dual-Entity (Koperasi KNMP & Asosiasi JE-P3) yang bergerak serempak.',
        domain: 3, domainColor: '#6A1B9A', badge: 'strategic',
        vision: '"Organisasi yang dirancang dengan baik memungkinkan orang biasa melakukan hal luar biasa."',
        dimensions: [{ label: 'Model', value: 'Dual-Entity (Koperasi KNMP & Asosiasi JE-P3)' }, { label: 'Skalabilitas', value: 'Dari 100 ke 83.763 desa' }],
        principles: ['Struktur organisasi mengikuti strategi, bukan sebaliknya'],
        xref: [17, 19, 33, 51] },
      { id: 19, code: 'PGA-19', name: 'Matriks Kewenangan Mutlak', eng: 'Role & Authority Matrix',
        desc: 'Ketegasan tentang siapa yang berhak mengambil keputusan dari level desa hingga global.',
        domain: 3, domainColor: '#6A1B9A', badge: 'strategic',
        vision: '"Kewenangan yang tidak jelas adalah resep kekacauan. Matriks ini memastikan setiap orang tahu apa yang boleh dan tidak boleh dilakukan."',
        dimensions: [{ label: 'Format', value: 'RACI Matrix' }, { label: 'Cakupan', value: 'Seluruh Fungsi & Level' }],
        principles: ['Setiap keputusan harus memiliki pemilik yang jelas'],
        xref: [17, 20, 22, 24] },
      { id: 20, code: 'PGA-20', name: 'Protokol Pengambilan Keputusan', eng: 'Decision-Making Protocol',
        desc: 'Mekanisme musyawarah mufakat dan voting proporsional yang mengunci keadilan.',
        domain: 3, domainColor: '#6A1B9A', badge: 'operational',
        vision: '"Keputusan terbaik bukan yang tercepat, tetapi yang paling terinformasi dan akuntabel."',
        dimensions: [{ label: 'Tingkatan', value: 'Tactical, Operational, Strategic' }, { label: 'SLA', value: 'Time-bound Decision' }],
        principles: ['Keputusan harus terdokumentasi dan dapat ditelusuri'],
        xref: [19, 22, 24, 67] },
      { id: 21, code: 'PGA-21', name: 'Perisai Hukum & Kepatuhan', eng: 'Legal Compliance Pack',
        desc: 'Instrumen untuk memastikan kita selalu berada di atas landasan hukum nasional dan internasional.',
        domain: 3, domainColor: '#6A1B9A', badge: 'operational',
        vision: '"Organisasi yang beroperasi tanpa perisai hukum adalah organisasi yang berjudi dengan masa depannya."',
        dimensions: [{ label: 'Cakupan', value: 'Peraturan Nasional & Internasional' }, { label: 'Update', value: 'Quarterly Review' }],
        principles: ['Kepatuhan hukum bukan pilihan, melainkan keharusan'],
        xref: [22, 23, 45, 46] },
      { id: 22, code: 'PGA-22', name: 'Konstitusi Agung & AD-ART', eng: 'Constitutional Documents',
        desc: 'Dokumen perjanjian tertinggi yang tidak bisa diubah sepihak, fondasi Republik Koperasi.',
        domain: 3, domainColor: '#6A1B9A', badge: 'strategic',
        vision: '"Konstitusi adalah janji tertulis antara generasi pendiri dan generasi penerus."',
        dimensions: [{ label: 'Status', value: 'Dokumen Tertinggi' }, { label: 'Perubahan', value: 'Membutuhkan Muskup 2/3' }],
        principles: ['Konstitusi melindungi dari kekuasaan yang sewenang-wenang'],
        xref: [5, 7, 19, 23] },
      { id: 23, code: 'PGA-23', name: 'Tata Aturan Kemitraan', eng: 'Contracting Framework',
        desc: 'Panduan memastikan setiap pihak luar yang bekerja sama dengan KNBMP tunduk pada etika kita.',
        domain: 3, domainColor: '#6A1B9A', badge: 'operational',
        vision: '"Kontrak yang baik bukan yang menguntungkan satu pihak, tetapi yang membuat semua pihak merasa dilindungi."',
        dimensions: [{ label: 'Template', value: 'Standard & Custom' }, { label: 'Review', value: 'Legal & Compliance' }],
        principles: ['Setiap kontrak harus adil dan transparan'],
        xref: [21, 22, 37, 47] },
      { id: 24, code: 'PGA-24', name: 'Registri Kebijakan', eng: 'Policy Register & Tracker',
        desc: 'Perpustakaan hukum internal untuk menjaga ketertiban peradaban.',
        domain: 3, domainColor: '#6A1B9A', badge: 'operational',
        vision: '"Organisasi yang tidak tahu kebijakannya sendiri adalah organisasi yang buta."',
        dimensions: [{ label: 'Format', value: 'Digital Register' }, { label: 'Akses', value: 'Seluruh Anggota' }],
        principles: ['Transparansi kebijakan adalah fondasi kepercayaan'],
        xref: [19, 20, 22, 72] },
    ],
  },
  {
    id: 4,
    code: 'D4',
    emoji: '⚙️',
    name: 'Product / Service / Solution',
    nameId: 'Produk & Layanan',
    nameSubtitle: 'Mesin Pembebas Rakyat',
    range: 'PGA-25 — PGA-32',
    color: '#008F3D',
    bgColor: 'rgba(0,143,61,0.08)',
    borderColor: 'border-l-[#008F3D]',
    description: 'Domain ini adalah senjata kita. Instrumen nyata (teknologi, aplikasi, hak-hak) yang mengubah penderitaan menjadi kesejahteraan. Di sinilah idealisme berubah menjadi produk yang bisa disentuh.',
    pillars: [
      { id: 25, code: 'PGA-25', name: 'Arsitektur 16 Hak Anggota', eng: 'Product / Service Architecture',
        desc: 'Arsitektur Super-App kopnusa.id yang mewujudkan 16 Hak Anggota menjadi layanan nyata melalui 12 modul platform terintegrasi. Setiap hak diwujudkan melalui modul spesifik: VMS (Village Management System), Health Dashboard, Agri Dashboard, Economy Tracker, Cooperative Governance, Marketplace, Fintech JP3 Pay, Logistics, Academy, Safety & Security, Cultural Heritage, dan Energy. Platform ini mengintegrasikan seluruh kelembagaan desa (PKK, BUMDes, Karang Taruna, Posyandu, Gapoktan, KUD, dll) ke dalam satu ekosistem digital tunggal.',
        domain: 4, domainColor: '#008F3D', badge: 'strategic',
        vision: '"Setiap anggota berhak atas layanan yang setara dengan martabatnya — bukan sisa, bukan murahan, tetapi yang terbaik."',
        dimensions: [
          { label: 'Hak', value: '16 Hak Anggota' },
          { label: 'Kategori', value: 'Produk, Layanan, Solusi' },
          { label: 'Super-App kopnusa.id', value: '12 modul terintegrasi' },
          { label: 'Modul 1: VMS', value: 'Dashboard desa terintegrasi — kependudukan, keuangan, aset, pembangunan' },
          { label: 'Modul 2: Health', value: 'Data stunting, imunisasi, sanitasi, air bersih, EMR terintegrasi BPJS' },
          { label: 'Modul 3: Agri', value: 'Jadwal tanam, irigasi, produksi, harga — Smart Farming Dashboard' },
          { label: 'Modul 4: Economy', value: 'Transaksi BUMDes, BUMDesMA, KUD, KDMP — laporan laba/rugi real-time' },
          { label: 'Modul 5: Governance', value: 'Voting, SHU distribution, keputusan RAT — blockchain Hyperledger' },
          { label: 'Modul 6: Marketplace', value: 'Zona Agri, Retail/UMKM, Jasa, Digital, Kesehatan, Spiritual, Ekspor, Energi' },
          { label: 'Modul 7: JP3 Pay', value: 'Pinjaman, tabungan, zakat, transfer — API Bank Himbara + BI' },
          { label: 'Modul 8-12', value: 'Logistics, Academy, Safety & Security, Cultural Heritage, Energy' },
        ],
        principles: [
          'Desain produk dimulai dari kebutuhan rakyat, bukan keinginan manajemen',
          'Setiap modul platform harus terintegrasi dengan lembaga desa yang sudah ada (PKK, BUMDes, Karang Taruna, dll)',
          'Super-App kopnusa.id bukan pengganti lembaga desa — ia adalah Digital Nervous System yang menghubungkan semua',
          'Interoperabilitas data dengan sistem pemerintah (SID, Prodeskel, Siskeudes) adalah kewajiban, bukan opsional',
          'Setiap modul harus menghasilkan data yang bermanfaat bagi seluruh ekosistem, bukan silo informasi',
        ],
        xref: [1, 9, 10, 13, 26, 28, 34, 37] },
      { id: 26, code: 'PGA-26', name: 'Spesifikasi Mesin Digital', eng: 'Product Requirement Document',
        desc: 'Desain teknis dari kopnusa.id, JP3 Pay, dan sistem blockchain penyokongnya.',
        domain: 4, domainColor: '#008F3D', badge: 'operational',
        vision: '"Mesin digital adalah jantung operasional KNBMP — ia harus sekuat dan setangguh tekad para pendiri."',
        dimensions: [{ label: 'Platform', value: 'kopnusa.id, JP3 Pay, Blockchain' }, { label: 'Standar', value: 'Enterprise-grade' }],
        principles: ['Teknologi melayani rakyat, bukan sebaliknya'],
        xref: [25, 27, 28, 67] },
      { id: 27, code: 'PGA-27', name: 'Peta Jalan Transformasi Digital', eng: 'Product Strategy & Roadmap',
        desc: 'Urutan peluncuran fitur dari mulai versi Alpha hingga OS Desa Berdikari paripurna.',
        domain: 4, domainColor: '#008F3D', badge: 'strategic',
        vision: '"Transformasi digital bukan soal teknologi — ia soal mengubah cara rakyat mengakses kedaulatan ekonomi."',
        dimensions: [{ label: 'Fase', value: 'Alpha → Beta → Full' }, { label: 'Timeline', value: 'MVP to OS Desa Berdikari' }],
        principles: ['Digitalisasi harus inklusif — tidak boleh meninggalkan desa tanpa internet'],
        xref: [9, 26, 28, 31] },
      { id: 28, code: 'PGA-28', name: 'Cetak Biru Sistem Saraf Desa', eng: 'System Architecture / Blueprint',
        desc: 'Bagaimana server, API pemerintah, dan smart contract saling terhubung tanpa jeda.',
        domain: 4, domainColor: '#008F3D', badge: 'operational',
        vision: '"Saraf desa menghubungkan setiap titik ekonomi dalam jaringan yang tidak bisa diputus."',
        dimensions: [{ label: 'Arsitektur', value: 'Distributed System' }, { label: 'Redundancy', value: 'Multi-node Backup' }],
        principles: ['Arsitektur harus tahan terhadap kegagalan node tunggal'],
        xref: [26, 27, 66, 67] },
      { id: 29, code: 'PGA-29', name: 'Peta Perjalanan Kehidupan Anggota', eng: 'User Journey Map',
        desc: 'Detik demi detik pengalaman emosional seorang petani sejak mendaftar hingga berhasil mengekspor produknya.',
        domain: 4, domainColor: '#008F3D', badge: 'operational',
        vision: '"Setiap sentuhan dengan anggota adalah kesempatan untuk membuktikan bahwa kedaulatan itu nyata."',
        dimensions: [{ label: 'Touchpoint', value: 'Onboarding to Loyalty' }, { label: 'Metric', value: 'NPS, Retention, Satisfaction' }],
        principles: ['User experience harus mencerminkan nilai-nilai organisasi'],
        xref: [2, 10, 25, 35] },
      { id: 30, code: 'PGA-30', name: 'Standar Mutu Kelas Dunia', eng: 'Quality Standard & Acceptance',
        desc: 'Janji kita bahwa produk buatan desa tidak boleh kalah kualitas dari produk multinasional.',
        domain: 4, domainColor: '#008F3D', badge: 'operational',
        vision: '"Kualitas kelas dunia bukan kemewahan — ia adalah hak setiap anggota KNBMP."',
        dimensions: [{ label: 'Standar', value: 'ISO & Custom' }, { label: 'Testing', value: 'Multi-layer QA' }],
        principles: ['Kualitas tidak bisa dinegosiasi — ia adalah janji kepada rakyat'],
        xref: [26, 31, 46, 67] },
      { id: 31, code: 'PGA-31', name: 'Dapur Inovasi Berkelanjutan', eng: 'Innovation Pipeline',
        desc: 'Sistem untuk terus melahirkan ide baru dari desa agar koperasi tidak pernah menua.',
        domain: 4, domainColor: '#008F3D', badge: 'strategic',
        vision: '"Inovasi bukan departemen — ia adalah mindset yang harus mengalir dalam setiap poros organisasi."',
        dimensions: [{ label: 'Pipeline', value: 'Idea to Production' }, { label: 'Budget', value: 'Revenue-linked' }],
        principles: ['Setiap anggota berhak mengusulkan inovasi'],
        xref: [25, 27, 30, 32] },
      { id: 32, code: 'PGA-32', name: 'Protokol Perubahan Platform', eng: 'Change Request Governance',
        desc: 'Cara aman dan demokratis untuk meng-upgrade sistem tanpa merusak data anggota.',
        domain: 4, domainColor: '#008F3D', badge: 'operational',
        vision: '"Perubahan tanpa tata kelola adalah kekacauan. Tata kelola tanpa fleksibilitas adalah kematian."',
        dimensions: [{ label: 'Proses', value: 'Request, Review, Approve, Deploy' }, { label: 'SLA', value: 'Defined per Priority' }],
        principles: ['Setiap perubahan harus memiliki risiko assessment'],
        xref: [8, 20, 24, 72] },
    ],
  },
  {
    id: 5,
    code: 'D5',
    emoji: '🚚',
    name: 'Operations & Delivery',
    nameId: 'Operasional',
    nameSubtitle: 'Urat Nadi & Pergerakan',
    range: 'PGA-33 — PGA-40',
    color: '#E65100',
    bgColor: 'rgba(230,81,0,0.08)',
    borderColor: 'border-l-[#E65100]',
    description: 'Sebuah sistem sehebat apapun akan mati tanpa eksekusi harian yang tangguh. Ini adalah mesin penggerak, rantai pasok, dan prosedur lapangan yang dijalankan setiap pagi.',
    pillars: [
      { id: 33, code: 'PGA-33', name: 'Kitab Suci Operasional', eng: 'Master Operational SOP',
        desc: 'Aturan dasar sehari-hari yang memastikan semua elemen berjalan seirama bagai jarum jam.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Operasional tanpa SOP adalah improvisasi. Improvisasi tanpa standar adalah risiko."',
        dimensions: [{ label: 'Cakupan', value: 'Seluruh Fungsi Operasional' }, { label: 'Format', value: 'Step-by-step Playbook' }],
        principles: ['SOP harus hidup dan diperbarui berkala'],
        xref: [18, 34, 35, 40] },
      { id: 34, code: 'PGA-34', name: 'Peta Aliran Proses Abadi', eng: 'Process Map End-to-End',
        desc: 'Visualisasi bagaimana gabah dari sawah menjadi uang di JP3 Pay tanpa hambatan. Operations manual untuk level Desa & Kecamatan yang menjadi fondasi Desa Cerdas Digital — 6 sub-pilar terintegrasi: Desa Digital (VMS dashboard terintegrasi), Desa Aman (Safety & Security Module), Desa Sehat (Health Dashboard terintegrasi BPJS), Desa Pintar (Education & Youth Hub via JE-P3 Academy), Desa Kaya (Family Economy Tracker), dan Desa Modern (Infrastructure & Heritage Portal). Setiap sub-pilar mengintegrasikan lembaga desa yang sudah ada (PKK, Karang Taruna, Posyandu, BUMDes, LPM, dll) ke dalam satu ekosistem operasional melalui kopnusa.id.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Proses yang terpetakan adalah proses yang bisa diperbaiki. Proses yang tak terlihat adalah proses yang tak bisa dipercaya."',
        dimensions: [
          { label: 'Metode', value: 'BPMN & Visual Map' },
          { label: 'Koneksi', value: 'Inter-process Dependencies' },
          { label: 'Desa Digital', value: 'VMS: Dashboard desa terintegrasi — kependudukan, keuangan, aset, pembangunan' },
          { label: 'Desa Aman', value: 'Safety & Security Module: CCTV monitoring, emergency alert, perlindungan warga' },
          { label: 'Desa Sehat', value: 'Health Dashboard: Data stunting, imunisasi, sanitasi, air bersih, EMR terintegrasi BPJS' },
          { label: 'Desa Pintar', value: 'Education & Youth Hub: JE-P3 Academy outlet, digital literacy, skill center' },
          { label: 'Desa Kaya', value: 'Family Economy Tracker: Pendapatan keluarga, program pemberdayaan, akses modal' },
          { label: 'Desa Modern', value: 'Infrastructure & Heritage Portal: Peta infrastruktur, maintenance, katalog budaya' },
          { label: 'KPI 2030', value: '83.763 desa terkoneksi, stunting turun 50%, 50M lulusan digital literacy' },
        ],
        principles: [
          'Setiap proses harus memiliki input, output, dan owner yang jelas',
          'Desa Cerdas Digital bukan konsep abstrak — ia adalah integrasi 6 sub-pilar yang menghubungkan lembaga desa existing ke platform kopnusa.id',
          'PKK adalah channel utama ke level rumah tangga — setiap kader PKK adalah agen operasional KNMP di desa',
          'Karang Taruna adalah pipeline SDM — calon agen logistik, kader digital, dan entrepreneur desa',
          'Interoperabilitas data antar-sub-pilar harus mulus — data Posyandu terhubung ke Health Dashboard, data BUMDes ke Economy Tracker',
          'Operasional desa harus bisa dijalankan oleh sumber daya lokal — bukan bergantung pada staf pusat',
        ],
        xref: [33, 35, 36, 38, 13, 25, 26, 28] },
      { id: 35, code: 'PGA-35', name: 'Panduan Pelayanan Paripurna', eng: 'Service Delivery Manual',
        desc: 'Standar bagaimana petugas koperasi memperlakukan anggota dengan martabat dan kehormatan.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Pelayanan paripurna bukan kemewahan — ia adalah standar minimum yang harus kami berikan kepada rakyat."',
        dimensions: [{ label: 'SLA', value: 'Response, Resolution, Satisfaction' }, { label: 'Channel', value: 'Omnichannel' }],
        principles: ['Kepuasan anggota adalah satu-satunya metrik yang benar-benar penting'],
        xref: [29, 33, 34, 40] },
      { id: 36, code: 'PGA-36', name: 'Panduan Pengadaan & Pemasok', eng: 'Procurement & Vendor Playbook',
        desc: 'Memastikan setiap pembelian koperasi bersih dari korupsi, suap, atau konflik kepentingan.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Pengadaan yang transparan adalah bukti bahwa organisasi ini benar-benar milik rakyat."',
        dimensions: [{ label: 'Prinsip', value: 'Transparansi & Zero Corruption' }, { label: 'Evaluasi', value: 'Scorecard System' }],
        principles: ['Setiap pengadaan harus bisa diaudit oleh anggota'],
        xref: [34, 37, 44, 46] },
      { id: 37, code: 'PGA-37', name: 'Tata Krama Kemitraan', eng: 'Partnership Playbook',
        desc: 'Panduan merangkul pihak ketiga (seperti Bank Himbara atau BUMDes) sebagai saudara seperjuangan.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Kemitraan sejati dibangun di atas rasa hormat, bukan di atas kepentingan sesaat."',
        dimensions: [{ label: 'Prinsip', value: 'Win-Win or No Deal' }, { label: 'Onboarding', value: 'Partner Vetting Process' }],
        principles: ['Setiap mitra harus menyepakati nilai-nilai KNBMP'],
        xref: [13, 14, 23, 36] },
      { id: 38, code: 'PGA-38', name: 'Protokol Pemadam Kebakaran', eng: 'Incident & Escalation SOP',
        desc: 'Cara kita merespons masalah, komplain, atau error sistem dalam hitungan menit.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Ketika kebakaran terjadi, yang menentukan bukan apakah itu terjadi, tetapi seberapa cepat kita memadamkannya."',
        dimensions: [{ label: 'Level', value: '1 (Minor) to 5 (Critical)' }, { label: 'Response', value: 'Defined per Level' }],
        principles: ['Setiap insiden harus memiliki post-mortem yang jujur'],
        xref: [34, 39, 40, 64] },
      { id: 39, code: 'PGA-39', name: 'Rencana Kebangkitan dari Bencana', eng: 'Business Continuity & Disaster Recovery',
        desc: 'Kepastian bahwa jika server mati atau terjadi gempa, data dan uang anggota tetap aman mutlak.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Organisasi yang hanya siap menghadapi hari baik bukan organisasi — ia adalah penjudi."',
        dimensions: [{ label: 'RTO', value: 'Recovery Time Objective' }, { label: 'RPO', value: 'Recovery Point Objective' }],
        principles: ['Business continuity harus diuji secara berkala, bukan hanya di atas kertas'],
        xref: [16, 38, 45, 66] },
      { id: 40, code: 'PGA-40', name: 'Panduan Pasukan Lapangan', eng: 'Field / Branch Deployment SOP',
        desc: 'Arahan bagi para pejuang KNBMP di 80.081 titik desa di seluruh penjuru negeri.',
        domain: 5, domainColor: '#E65100', badge: 'operational',
        vision: '"Pasukan lapangan adalah wajah KNBMP di setiap desa — mereka harus menjadi yang terbaik."',
        dimensions: [{ label: 'Deployment', value: '80.081 Titik Desa' }, { label: 'Support', value: 'Central & Regional' }],
        principles: ['Setiap petugas lapangan adalah duta kedaulatan ekonomi'],
        xref: [12, 33, 35, 38] },
    ],
  },
  {
    id: 6,
    code: 'D6',
    emoji: '💰',
    name: 'Finance, Risk & Control',
    nameId: 'Keuangan & Risiko',
    nameSubtitle: 'Darah, Benteng, & Ketahanan',
    range: 'PGA-41 — PGA-48',
    color: '#B01C28',
    bgColor: 'rgba(176,28,40,0.08)',
    borderColor: 'border-l-[#B01C28]',
    description: 'Ekonomi yang kuat membutuhkan pengelolaan keuangan yang suci. Domain ini menjaga agar tidak ada satu rupiah pun hak anggota yang tercecer, dan koperasi selalu siap menghadapi badai ekonomi.',
    pillars: [
      { id: 41, code: 'PGA-41', name: 'Anatomi Keuangan Masa Depan', eng: 'Financial Model & Projection',
        desc: 'Proyeksi matematis menuju target transaksi Rp 500 Triliun pada tahun 2045.',
        domain: 6, domainColor: '#B01C28', badge: 'strategic',
        vision: '"Keuangan bukan hanya angka — ia adalah cermin keberlanjutan peradaban."',
        dimensions: [{ label: 'Target 2045', value: 'Rp 500 Triliun Transaksi' }, { label: 'Horizon', value: '5, 10, 25, 50 Tahun' }],
        principles: ['Proyeksi keuangan harus konservatif dalam pendapatan, optimis dalam penghematan'],
        xref: [9, 42, 43, 47] },
      { id: 42, code: 'PGA-42', name: 'Hitungan Nadi Ekonomi', eng: 'Unit Economics',
        desc: 'Bukti bahwa setiap transaksi (sekecil apapun di desa) menghasilkan profit margin yang sehat dan masuk akal.',
        domain: 6, domainColor: '#B01C28', badge: 'strategic',
        vision: '"Jika nadi ekonomi per unit tidak sehat, maka ekosistem seluruhnya akan kolaps."',
        dimensions: [{ label: 'Metrics', value: 'CAC, LTV, Contribution Margin' }, { label: 'BEP', value: 'Per Desa, Per Domain' }],
        principles: ['Unit economics yang positif adalah syarat non-negotiable ekspansi'],
        xref: [41, 43, 44, 61] },
      { id: 43, code: 'PGA-43', name: 'Protokol Kendali Kas', eng: 'Budgeting & Cash Control SOP',
        desc: 'Disiplin besi dalam menjaga arus kas agar koperasi tidak pernah kehabisan nafas.',
        domain: 6, domainColor: '#B01C28', badge: 'operational',
        vision: '"Setiap rupiah milik rakyat harus dipertanggungjawabkan seolah ia satu-satunya rupiah yang kita miliki."',
        dimensions: [{ label: 'Prinsip', value: 'Zero-based Budgeting' }, { label: 'Approval', value: 'Multi-tier Authorization' }],
        principles: ['Tidak ada pengeluaran tanpa persetujuan dan pertanggungjawaban'],
        xref: [41, 42, 44, 48] },
      { id: 44, code: 'PGA-44', name: 'Mesin Penghasil Kemakmuran', eng: 'Revenue Model & Monetization',
        desc: 'Darimana KNBMP mendapatkan uang secara etis tanpa harus memeras keringat anggotanya.',
        domain: 6, domainColor: '#B01C28', badge: 'strategic',
        vision: '"Kemakmuran bukan tujuan — ia adalah hasil dari sistem yang dirancang dengan benar."',
        dimensions: [{ label: 'Stream', value: 'Multiple Revenue Streams' }, { label: 'Distribution', value: 'Fair Value Sharing' }],
        principles: ['Revenue harus mengalir secara adil ke seluruh lapisan ekosistem'],
        xref: [25, 36, 42, 47] },
      { id: 45, code: 'PGA-45', name: 'Peta Radar Ancaman', eng: 'Risk Register & Mitigation Plan',
        desc: 'Identifikasi setiap bahaya (inflasi, gagal panen, regulasi) dan perisai untuk menangkalnya.',
        domain: 6, domainColor: '#B01C28', badge: 'strategic',
        vision: '"Risiko yang tidak dipetakan adalah risiko yang tidak bisa dikelola."',
        dimensions: [{ label: 'Framework', value: 'COSO ERM' }, { label: 'Review', value: 'Monthly Risk Committee' }],
        principles: ['Setiap risiko harus memiliki pemilik dan rencana mitigasi'],
        xref: [15, 16, 39, 46] },
      { id: 46, code: 'PGA-46', name: 'Mata Langit Transparansi', eng: 'Audit & Internal Control',
        desc: 'Sistem pengawasan (termasuk Blockchain Audit Trail) yang memastikan zero corruption.',
        domain: 6, domainColor: '#B01C28', badge: 'operational',
        vision: '"Audit bukan tentang mencuri kesalahan — ia tentang memastikan kepercayaan tidak pernah pudar."',
        dimensions: [{ label: 'Jenis', value: 'Internal, Eksternal, Blockchain Audit Trail' }, { label: 'Independensi', value: 'Direct to Board' }],
        principles: ['Audit harus independen dan dilindungi dari tekanan'],
        xref: [21, 30, 43, 48] },
      { id: 47, code: 'PGA-47', name: 'Memorandum Kepercayaan Investor', eng: 'Investment / Funding Memorandum',
        desc: 'Dokumen suci untuk menarik impact investor tanpa pernah menggadaikan kedaulatan koperasi.',
        domain: 6, domainColor: '#B01C28', badge: 'strategic',
        vision: '"Investor yang tepat bukan yang memberi uang terbanyak, tetapi yang memahami visi peradaban."',
        dimensions: [{ label: 'Tipe', value: 'Equity, Debt, Grant' }, { label: 'Terms', value: 'Founder-friendly' }],
        principles: ['Setiap investasi harus selaras dengan misi kedaulatan ekonomi'],
        xref: [23, 41, 44, 63] },
      { id: 48, code: 'PGA-48', name: 'Penjaga Harta Karun', eng: 'Treasury, Asset & Reserve Policy',
        desc: 'Aturan menjaga dana cadangan agar KNBMP terus kokoh melewati krisis ekonomi sedahsyat apapun.',
        domain: 6, domainColor: '#B01C28', badge: 'operational',
        vision: '"Harta yang tidak dijaga adalah harta yang menunggu untuk dirampas."',
        dimensions: [{ label: 'Cadangan', value: 'Operational & Strategic Reserve' }, { label: 'Investasi', value: 'Conservative Portfolio' }],
        principles: ['Aset strategis tidak boleh dijadikan jaminan utang spekulatif'],
        xref: [41, 43, 46, 47] },
    ],
  },
  {
    id: 7,
    code: 'D7',
    emoji: '👥',
    name: 'People, Culture & Leadership',
    nameId: 'Sumber Daya & Budaya',
    nameSubtitle: 'Manusia & Penjaga Api',
    range: 'PGA-49 — PGA-56',
    color: '#00695C',
    bgColor: 'rgba(0,105,92,0.08)',
    borderColor: 'border-l-[#00695C]',
    description: 'Koperasi bukan tentang tumpukan modal, melainkan kumpulan manusia. Domain ini memastikan kita mendidik kader, menjaga budaya gotong royong, dan menyiapkan pemimpin masa depan.',
    pillars: [
      { id: 49, code: 'PGA-49', name: 'Seni Menemukan Bintang', eng: 'Talent & Recruitment Framework',
        desc: 'Cara kita menjaring bibit unggul dari desa untuk memimpin korporasi global.',
        domain: 7, domainColor: '#00695C', badge: 'operational',
        vision: '"Bintang tidak lahir dari selebaran — ia lahir dari proses penemuan yang sabar dan cermat."',
        dimensions: [{ label: 'Proses', value: 'Multi-stage Selection' }, { label: 'Kriteria', value: 'Competence & Character' }],
        principles: ['Karakter lebih penting dari kompetensi — kompetensi bisa diajarkan, karakter tidak'],
        xref: [50, 51, 53, 54] },
      { id: 50, code: 'PGA-50', name: 'Model Kepemimpinan Merah Putih', eng: 'Leadership Model',
        desc: 'Profil pemimpin KNBMP: merakyat seperti Santri Angon, tangguh seperti Prabu Danling.',
        domain: 7, domainColor: '#00695C', badge: 'strategic',
        vision: '"Pemimpin yang sesungguhnya bukan yang dilayani, tetapi yang melayani."',
        dimensions: [{ label: 'Filosofi', value: 'Servant Leadership' }, { label: 'Level', value: 'Front-line to Board' }],
        principles: ['Setiap pemimpin harus melewati uji lapangan sebelum naik jabatan'],
        xref: [3, 17, 51, 56] },
      { id: 51, code: 'PGA-51', name: 'Panduan Pengelolaan SDM', eng: 'HR Operating Manual',
        desc: 'Mengurus kesejahteraan ribuan kader dan agen digital secara manusiawi dan berkeadilan.',
        domain: 7, domainColor: '#00695C', badge: 'operational',
        vision: '"SDM bukan sumber daya — ia adalah manusia. Manusia yang harus diperlakukan dengan martabat."',
        dimensions: [{ label: 'Lifecycle', value: 'Hire to Retire' }, { label: 'Wellbeing', value: 'Physical, Mental, Financial' }],
        principles: ['Kesejahteraan karyawan adalah investasi, bukan biaya'],
        xref: [18, 49, 50, 52] },
      { id: 52, code: 'PGA-52', name: 'Cermin Prestasi Objektif', eng: 'Performance Management System',
        desc: 'Menilai kinerja berdasarkan dampak nyata ke masyarakat, bukan sekadar menjilat atasan.',
        domain: 7, domainColor: '#00695C', badge: 'operational',
        vision: '"Evaluasi yang adil membangun kepercayaan. Evaluasi yang membangun menciptakan keunggulan."',
        dimensions: [{ label: 'Sistem', value: 'OKR + KPI' }, { label: 'Siklus', value: 'Quarterly Review' }],
        principles: ['Setiap orang berhak tahu di mana ia berdiri dan bagaimana ia bisa berkembang'],
        xref: [50, 51, 53, 67] },
      { id: 53, code: 'PGA-53', name: 'Kawah Candradimuka Akademi', eng: 'Training & Certification',
        desc: 'Sistem pendidikan (JE-P3 Academy) untuk mengubah petani biasa menjadi eksportir kelas dunia.',
        domain: 7, domainColor: '#00695C', badge: 'operational',
        vision: '"Candradimuka — tempat para kesatria ditempa menjadi baja yang tak bisa dilenturkan."',
        dimensions: [{ label: 'Program', value: 'JE-P3 Academy' }, { label: 'Sertifikasi', value: 'Internal & External' }],
        principles: ['Setiap anggota berhak mengakses program pengembangan diri'],
        xref: [49, 51, 52, 54] },
      { id: 54, code: 'PGA-54', name: 'Kode Sandi Budaya', eng: 'Culture Code',
        desc: 'DNA kita; Gotong Royong 4.0 yang dipraktikkan, bukan sekadar dijadikan slogan.',
        domain: 7, domainColor: '#00695C', badge: 'strategic',
        vision: '"Budaya adalah apa yang kita lakukan ketika tidak ada yang melihat."',
        dimensions: [{ label: 'Pilar', value: 'Values, Rituals, Heroes, Symbols' }, { label: 'Enforcement', value: 'Culture Guardians' }],
        principles: ['Budaya harus dijaga secara aktif, bukan dibiarkan tumbuh liar'],
        xref: [3, 5, 50, 55] },
      { id: 55, code: 'PGA-55', name: 'Sumpah Etika Kesatria', eng: 'Ethics & Conduct Code',
        desc: 'Garis batas absolut antara yang hak dan yang batil dalam berbisnis.',
        domain: 7, domainColor: '#00695C', badge: 'strategic',
        vision: '"Etika bukan aturan — ia adalah kompas jiwa yang menuntun setiap keputusan."',
        dimensions: [{ label: 'Prinsip', value: 'Zero Tolerance for Violations' }, { label: 'Reporting', value: 'Whistleblower Protection' }],
        principles: ['Pelanggaran etika harus ditindak tanpa pandang bulu'],
        xref: [5, 21, 54, 56] },
      { id: 56, code: 'PGA-56', name: 'Rantai Pewaris Peradaban', eng: 'Succession & Continuity Plan',
        desc: 'Persiapan sistematis agar ketika para Pendiri tiada, KNBMP justru berlari semakin kencang.',
        domain: 7, domainColor: '#00695C', badge: 'strategic',
        vision: '"Organisasi yang hebat bukan yang bergantung pada satu orang — ia adalah yang memastikan kehebatan bertahan melampaui generasi."',
        dimensions: [{ label: 'Plan', value: 'Emergency & Strategic Succession' }, { label: 'Horizon', value: '7-Year Pipeline' }],
        principles: ['Suksesi harus direncanakan jauh sebelum dibutuhkan'],
        xref: [8, 50, 55, 71] },
    ],
  },
  {
    id: 8,
    code: 'D8',
    emoji: '📢',
    name: 'Brand, Growth & Stakeholders',
    nameId: 'Merek & Pertumbuhan',
    nameSubtitle: 'Suara & Wajah Peradaban',
    range: 'PGA-57 — PGA-64',
    color: '#AD1457',
    bgColor: 'rgba(173,20,87,0.08)',
    borderColor: 'border-l-[#AD1457]',
    description: 'Bagaimana kita berbicara kepada dunia. Bagaimana kita menancapkan citra bahwa desa bukan lagi objek kelemahan, melainkan subjek kedaulatan.',
    pillars: [
      { id: 57, code: 'PGA-57', name: 'Estetika Kedaulatan', eng: 'Brand & Communication Guideline',
        desc: 'Standar visual dan bahasa yang menjadikan KNBMP tampak lebih megah dari korporasi asing.',
        domain: 8, domainColor: '#AD1457', badge: 'strategic',
        vision: '"Merek bukan logo — merek adalah janji yang diucapkan setiap hari melalui setiap interaksi."',
        dimensions: [{ label: 'Identity', value: 'Visual, Verbal, Digital' }, { label: 'Consistency', value: '100% Brand Compliance' }],
        principles: ['Setiap elemen visual harus mencerminkan kedaulatan dan martabat'],
        xref: [6, 58, 59, 63] },
      { id: 58, code: 'PGA-58', name: 'Matriks Narasi Penakluk Pikiran', eng: 'Narrative & Messaging',
        desc: 'Kumpulan pesan kunci ("Desa Tidak Lagi Minta — Desa Kini Memberi") yang disesuaikan untuk setiap audiens.',
        domain: 8, domainColor: '#AD1457', badge: 'strategic',
        vision: '"Narasi yang tepat pada waktu yang tepat bisa menggerakkan bangsa."',
        dimensions: [{ label: 'Framework', value: 'Hero, Problem, Solution, Vision' }, { label: 'Channel', value: 'All Media' }],
        principles: ['Narasi harus jujur, kuat, dan menginspirasi — bukan manipulatif'],
        xref: [4, 7, 57, 64] },
      { id: 59, code: 'PGA-59', name: 'Strategi Api Komunitas', eng: 'Community & Engagement',
        desc: 'Cara menyalakan semangat emosional warga agar bangga mengenakan seragam KNBMP.',
        domain: 8, domainColor: '#AD1457', badge: 'operational',
        vision: '"Komunitas yang kuat bukan yang paling besar, tetapi yang paling saling peduli."',
        dimensions: [{ label: 'Platform', value: 'Digital & Physical' }, { label: 'Metric', value: 'Engagement, Advocacy, Growth' }],
        principles: ['Komunitas dibangun oleh anggota, bukan untuk anggota'],
        xref: [57, 58, 60, 61] },
      { id: 60, code: 'PGA-60', name: 'Konstelasi Pemangku Kepentingan', eng: 'Stakeholder Map',
        desc: 'Pemetaan siapa kawan sejati, siapa pihak netral, dan siapa penentang yang harus diwaspadai.',
        domain: 8, domainColor: '#AD1457', badge: 'strategic',
        vision: '"Pemetaan yang akurat memungkinkan kita bergerak tanpa menginjak kaki siapa pun."',
        dimensions: [{ label: 'Map', value: 'Power-Interest Matrix' }, { label: 'Strategy', value: 'Per Segment' }],
        principles: ['Setiap pemangku kepentingan harus dipahami, bukan diabaikan'],
        xref: [13, 14, 59, 62] },
      { id: 61, code: 'PGA-61', name: 'Buku Pintar Ekspansi', eng: 'Sales / Acquisition Playbook',
        desc: 'Teknik merekrut jutaan anggota baru lewat kekuatan jaringan organik dari mulut ke mulut.',
        domain: 8, domainColor: '#AD1457', badge: 'operational',
        vision: '"Ekspansi tanpa playbook adalah ekspansi tanpa arah."',
        dimensions: [{ label: 'Funnel', value: 'Awareness to Activation' }, { label: 'Conversion', value: 'Data-driven Optimization' }],
        principles: ['Akuisisi harus etis dan berkelanjutan — bukan agresif dan manipulatif'],
        xref: [11, 12, 42, 60] },
      { id: 62, code: 'PGA-62', name: 'Diplomasi Pemerintahan', eng: 'Public Affairs / Gov. Relations',
        desc: 'Seni berdansa dengan regulasi, menjadikan pemerintah sebagai katalisator, bukan penghambat.',
        domain: 8, domainColor: '#AD1457', badge: 'strategic',
        vision: '"Pemerintah bukan musuh — ia adalah mitra yang harus diyakinkan bahwa kedaulatan rakyat adalah kepentingan bersama."',
        dimensions: [{ label: 'Level', value: 'Pusat, Provinsi, Kabupaten, Desa' }, { label: 'Approach', value: 'Non-partisan' }],
        principles: ['Hubungan pemerintahan harus berbasis data dan bukti, bukan sentimen'],
        xref: [14, 21, 60, 64] },
      { id: 63, code: 'PGA-63', name: 'Deklarasi Mengguncang Investor', eng: 'Investor / Partner Deck',
        desc: 'Senjata pamungkas CEO (Drs. H. Arif Rachman Hakim) untuk menaklukkan panggung global.',
        domain: 8, domainColor: '#AD1457', badge: 'strategic',
        vision: '"Presentasi yang hebat bukan yang paling cantik, tetapi yang paling menggerakkan."',
        dimensions: [{ label: 'Format', value: 'Slide, Video, One-pager' }, { label: 'Update', value: 'Quarterly' }],
        principles: ['Setiap klaim dalam presentasi harus didukung data yang bisa diverifikasi'],
        xref: [41, 47, 57, 61] },
      { id: 64, code: 'PGA-64', name: 'Manajemen Krisis & Badai', eng: 'Media & Crisis Communication',
        desc: 'Protokol satu pintu jika koperasi diserang secara politik atau dihantam rumor di media sosial.',
        domain: 8, domainColor: '#AD1457', badge: 'operational',
        vision: '"Badai akan datang. Yang membedakan adalah apakah kita siap atau tidak."',
        dimensions: [{ label: 'Protocol', value: 'Golden Hour Response' }, { label: 'Team', value: 'Crisis Task Force' }],
        principles: ['Kejujuran adalah satu-satunya strategi krisis yang berkelanjutan'],
        xref: [16, 38, 58, 62] },
    ],
  },
  {
    id: 9,
    code: 'D9',
    emoji: '💾',
    name: 'Data, Intelligence & Legacy',
    nameId: 'Data & Warisan',
    nameSubtitle: 'Ingatan & Warisan Abadi',
    range: 'PGA-65 — PGA-72',
    color: '#1565C0',
    bgColor: 'rgba(21,101,192,0.08)',
    borderColor: 'border-l-[#1565C0]',
    description: 'Domain terakhir dan paling sakral. Di sinilah ingatan masa lalu, kecerdasan masa kini, dan warisan masa depan dikunci dalam brankas digital peradaban.',
    pillars: [
      { id: 65, code: 'PGA-65', name: 'Kedaulatan Data Suci', eng: 'Data Governance & Privacy',
        desc: 'Janji absolut bahwa data anggota tidak akan pernah dijual (sesuai UU PDP).',
        domain: 9, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Data rakyat adalah harta suci yang tidak boleh diperjualbelikan."',
        dimensions: [{ label: 'Prinsip', value: 'Data Sovereignty' }, { label: 'Compliance', value: 'UU PDP & International' }],
        principles: ['Data anggota adalah milik anggota — KNBMP hanya menjaga'],
        xref: [28, 66, 67, 70] },
      { id: 66, code: 'PGA-66', name: 'Benteng Pertahanan Siber', eng: 'Security & Cyber Compliance',
        desc: 'Pertahanan digital kelas militer (quantum-ready) untuk melindungi aset ekosistem.',
        domain: 9, domainColor: '#1565C0', badge: 'operational',
        vision: '"Keamanan siber bukan biaya — ia adalah jaminan bahwa kepercayaan rakyat tidak akan dikhianati."',
        dimensions: [{ label: 'Framework', value: 'Zero Trust Architecture' }, { label: 'Testing', value: 'Continuous Pen-test' }],
        principles: ['Security by design, bukan security as afterthought'],
        xref: [15, 28, 39, 65] },
      { id: 67, code: 'PGA-67', name: 'Panel Kontrol Alam Semesta', eng: 'KPI Dashboard & North Star Metrics',
        desc: 'Indikator real-time untuk memantau detak jantung ekonomi di 83.763 desa.',
        domain: 9, domainColor: '#1565C0', badge: 'operational',
        vision: '"Apa yang tidak terukur tidak bisa diperbaiki. Panel kontrol ini memastikan kita selalu tahu di mana kita berdiri."',
        dimensions: [{ label: 'North Star', value: 'Kedaulatan Ekonomi Index' }, { label: 'Dashboard', value: 'Real-time & Historical' }],
        principles: ['Metric yang benar lebih penting dari metric yang banyak'],
        xref: [20, 26, 30, 72] },
      { id: 68, code: 'PGA-68', name: 'Perpustakaan Kebijaksanaan', eng: 'Knowledge Management',
        desc: 'Mengubah pengalaman lapangan anggota menjadi ensiklopedia digital yang bisa diakses generasi penerus.',
        domain: 9, domainColor: '#1565C0', badge: 'operational',
        vision: '"Organisasi yang lupa pelajarannya akan mengulang kesalahannya. Perpustakaan ini memastikan kebijaksanaan tidak pernah hilang."',
        dimensions: [{ label: 'System', value: 'Centralized Knowledge Base' }, { label: 'Akses', value: 'Role-based Permission' }],
        principles: ['Pengetahuan harus mengalir ke seluruh poros organisasi'],
        xref: [32, 53, 67, 69] },
      { id: 69, code: 'PGA-69', name: 'Radar Intelijen Ekonomi', eng: 'Research & Benchmark Register',
        desc: 'Mata tajam KNBMP dalam menganalisis pergerakan pasar global, tren harga komoditas, dan pergerakan kompetitor.',
        domain: 9, domainColor: '#1565C0', badge: 'operational',
        vision: '"Organisasi yang buta terhadap lingkungannya akan tersesat."',
        dimensions: [{ label: 'Riset', value: 'Market, Komoditas, Kompetitor' }, { label: 'Frequency', value: 'Continuous Monitoring' }],
        principles: ['Keputusan harus didasarkan pada data, bukan asumsi'],
        xref: [11, 45, 67, 68] },
      { id: 70, code: 'PGA-70', name: 'Bakti Pada Bumi & Manusia', eng: 'ESG / Sustainability Framework',
        desc: 'Memastikan keuntungan kita tidak merusak alam, menghormati hak perempuan, dan ramah lingkungan.',
        domain: 9, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Kita tidak mewarisi bumi dari nenek moyang — kita meminjamnya dari anak cucu."',
        dimensions: [{ label: 'Framework', value: 'ESG Triple Bottom Line' }, { label: 'Reporting', value: 'Annual Sustainability Report' }],
        principles: ['Keberlanjutan bukan departemen — ia adalah cara hidup organisasi'],
        xref: [4, 5, 65, 71] },
      { id: 71, code: 'PGA-71', name: 'Perjanjian Suci 100 Tahun', eng: 'Legacy / 100-Year Covenant',
        desc: 'Sumpah abadi yang dikunci dalam Blockchain bahwa KNMP tidak akan pernah dikonversi menjadi perusahaan swasta (PT).',
        domain: 9, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Perjanjian ini mengikat generasi hari ini dengan generasi 100 tahun dari sekarang."',
        dimensions: [{ label: 'Horizon', value: '2025–2125' }, { label: 'Binding', value: 'Blockchain-locked' }],
        principles: ['Warisan tidak dibangun sehari — ia dirajut setiap hari'],
        xref: [1, 4, 7, 72] },
      { id: 72, code: 'PGA-72', name: 'Indeks Master & Kontrol Semesta', eng: 'Master Index & Document Control',
        desc: 'Kunci gembok dari ke-72 dokumen ini, menjaga integritas, versi, dan orisinalitas arsitektur peradaban.',
        domain: 9, domainColor: '#1565C0', badge: 'strategic',
        vision: '"Dokumen ini adalah otak dari seluruh arsitektur — ia memastikan setiap pilar tetap sinkron dan setiap perubahan tercatat."',
        dimensions: [{ label: 'Scope', value: 'All 72 Pillars' }, { label: 'Control', value: 'Version & Change Log' }],
        principles: ['Master Index adalah satu-satunya sumber kebenaran mutlak'],
        xref: [8, 24, 32, 67] },
    ],
  },
];

export const allPillars: Pillar[] = domains.flatMap(d => d.pillars);

export function getPillarByNumber(num: number): Pillar | undefined {
  return allPillars.find(p => p.id === num);
}

export function getDomainForPillar(pillarId: number): Domain | undefined {
  return domains.find(d => d.pillars.some(p => p.id === pillarId));
}
